<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-06-26 09:37
=======
# Generated by Django 3.1.4 on 2021-06-26 10:07
>>>>>>> a1333f8bd323e9c4ea3bd250179c67c04d7fc87d

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> a1333f8bd323e9c4ea3bd250179c67c04d7fc87d
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=150, null=True)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
                ('lease_rate', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('view_fee', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='properties')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.profile')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> a1333f8bd323e9c4ea3bd250179c67c04d7fc87d
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> a1333f8bd323e9c4ea3bd250179c67c04d7fc87d
                ('front_image', models.ImageField(upload_to='properties')),
                ('back_image', models.ImageField(upload_to='properties')),
                ('side_image', models.ImageField(upload_to='properties')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, to='properties.Tag'),
        ),
    ]
